services:
  postgres:
    image: postgres:17
    container_name: bi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - bi-postgres-data:/var/lib/postgresql/data

volumes:
  bi-postgres-data:
