spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/dev

logging:
  level:
    org:
      springframework=DEBUG:

dss:
  reference-date: 2026-04-04
