###
GET http://localhost:8081/api/bins/binmap
Accept: application/json

###
GET http://localhost:8081/api/bins/binlist
Accept: application/json

###
GET http://localhost:8081/api/bins/bindetails/1
Accept: application/json
