###
GET http://localhost:8080/api/bins/binmap
Accept: application/json

###
GET http://localhost:8080/api/bins/binlist
Accept: application/json

###
GET http://localhost:8080/api/bins/bindetails/1
Accept: application/json

###
GET http://localhost:8080/api/bins/bindetails/1/visits
Accept: application/json

###
GET http://localhost:8080/api/bins/bindetails/1/visits/csv
Accept: text/csv; charset=utf-8
